// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Pegasus.Data
{
    public class BarangayConfiguration : IEntityTypeConfiguration<Barangay>
    {
        public void Configure(EntityTypeBuilder<Barangay> entity)
        {
            entity.HasOne(d => d.Lgu)
                .WithMany(p => p.Barangay)
                .HasForeignKey(d => d.LguId)
                .HasConstraintName("FK_Barangay_LguProfile");
        }
    }
}
