// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pegasus.Data
{
    public partial class UserAgents
    {
        public UserAgents()
        {
            PersonProfile = new HashSet<PersonProfile>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "text")]
        public string Fullname { get; set; }
        public int? PIN { get; set; }
        [Column(TypeName = "text")]
        public string Department { get; set; }

        [InverseProperty("AgentNavigation")]
        public virtual ICollection<PersonProfile> PersonProfile { get; set; }
    }
}